on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt
          .venv/bin/python main.py --year 2025 --highlight-past > renders/svg/latest.svg
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update latest" || true
          git push
        env:
          GH_TOKEN: ${{ github.token }}
